### ISSUE TITLE
LTI 1.3 and EdX

### ISSUE THREAD

**Issue by sean-morris** [jupyterhub/ltiauthenticator#202]
I am struggling to get the LTI 1.3 authenticator working with EdX.

I am being given this configuration from EdX:
- Client ID: ##client-id##
- Deployment ID: 1
- Keyset URL: https://courses.edx.org/api/lti_consumer/v1/public_keysets/##ketset-id##
- Access Token URL: https://courses.edx.org/api/lti_consumer/v1/token/##ketset-id##
- Login URL: https://courses.edx.org/api/lti_consumer/v1/launch/ 

I integrated them into my helm deployment yaml:
```
config:
       JupyterHub:
              authenticator_class: ltiauthenticator.lti13.auth.LTI13Authenticator
      LTI13Authenticator:
             issuer: https://courses.edx.org
             authorize_url: https://courses.edx.org/api/lti_consumer/v1/launch/
             jwks_endpoint: https://courses.edx.org/api/lti_consumer/v1/public_keysets/##keyset_id##
             client_id: 
                - ##client-id##
```
 
I configured the EdX LTI tool with the following:
- Tool Launch URL: https://edx-staging.datahub.berkeley.edu
- Registered Redirect URIs: ["https://edx-staging.datahub.berkeley.edu/hub/lti13/oauth_callback"]
- Tool Initiate Login URL: https://edx-staging.datahub.berkeley.edu/hub/lti13/oauth_login
- Tool Public Key Mode: Set to KeySet URL
- Tool Keyset URL --> not set -- I think this is correct from the documentation ... otherwise what is it for my hub?
- Custom Parameters (allows nbgitpuller link) : ["next=/hub/user-redirect/git-sync?repo=https://github.com/data-88e/Data88e-online&subPath=labs/lab04/lab04.ipynb"]

EdX gives me this message when I save the config:
>  LTI 1.3 Launches can only be performed from the LMS.
>  To set up the LTI integration, you need to register the LMS in the tool with the information provided below.
> - Client ID: ##client-id##
> - Deployment ID: 1
> - Keyset URL: https://courses.edx.org/api/lti_consumer/v1/public_keysets/##ketset-id##
> - Access Token URL: https://courses.edx.org/api/lti_consumer/v1/token/##ketset-id##
> - Login URL: https://courses.edx.org/api/lti_consumer/v1/launch/ 

Any ideas or documentation would be great.
