### ISSUE TITLE
Example in README.md with use together with the JupyterHub Helm chart is outdated

### ISSUE THREAD

**Issue by nammotd** [jupyterhub/ltiauthenticator#72]
I failed installing Jupyterhub with ltiauthenticator by using helm.
My helm value is configured as this instruction https://github.com/jupyterhub/ltiauthenticator#custom-configuration-with-jupyterhubs-helm-chart

And the hub pod is CrashLoopBackOff with this error
```(⎈ |dev-orbiter:jupyter)(base) ➜  jupyter git:(IM-13) ✗ k logs pods/hub-6d56dfd8c4-jpbsb
Loading /usr/local/etc/jupyterhub/secret/values.yaml

No config at /usr/local/etc/jupyterhub/existing-secret/values.yaml

[C 2021-09-25 08:33:13.891 JupyterHub application:89] Bad config encountered during initialization: The 'authenticator_class' trait of <jupyterhub.app.JupyterHub object at 0x7f6c731dd0a0> instance must be a type, but 'lti' could not be importe```

**Comment by jgwerner** [comment]
@nammotd thanks for reporting this issue and apologies for taking soling to respond. Could you confirm the version of the Helm chart you are using? Based on that I could help reproduce the error in a fresh cluster.

**Comment by consideRatio** [comment]
The Z2JH Helm chart does no longer support a shorthand like `lti`, but you should write...

```yaml
hub:
  config:
    JupyterHub:
      authenticator_class: ltiauthenticator.LTIAuthenticator # LTI 1.1
      # authenticator_class: ltiauthenticator.lti13.auth.LTI13Authenticator # LTI 1.3
```

The example in https://github.com/jupyterhub/ltiauthenticator#custom-configuration-with-jupyterhubs-helm-chart is outdated.
